image: sbtscala/scala-sbt:eclipse-temurin-focal-17.0.5_8_1.8.2_2.13.10

before_script:
  - apt-get update
  - apt-get install -y make gcc-arm-linux-gnueabi qemu-user


build:
  stage: build
  script:
    - make
