image: gumjoe/wacc-ci-scala:arm32

build:
  stage: build
  script:
    - scala-cli compile .

test:
  stage: test
  script:
    - scala-cli test .

test-integration:
  stage: test
  script:
    - git submodule update --init --recursive
    - make test