image: kryptos12/wacc-04:0.0.5

build:
  stage: build
  script:
    - scala-cli compile .

test:
  stage: test
  script:
    - scala-cli test .

test-integration:
  stage: test
  script:
    - git submodule update --init --recursive
    - make test