image: kryptos12/wacc-04:0.0.3

build:
  stage: build
  script:
    - scala-cli compile .

test:
  stage: test
  script:
    - scala-cli test .

test-integration:
  stage: test
  script:
    - sudo apt-get update
    - sudo apt-get install gcc-aarch64-linux-gnu qemu-user
    - git submodule update --init --recursive
    - make test