image: openjdk:11

build:
  stage: build
  script:
    - apt-get update -y
    - apt-get -y install make
    - curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
    - make
